### ISSUE TITLE
out of date code base 

### ISSUE THREAD

**Issue by kieran-hamill-mobil-i** [Oliver-Binns/tube-status-ios#1]
looks like the recent changes after release of widgets has left your code base outdated with code completion errors.
 shame cause its the only reference online to dealing with url calls in regards to widgets.
 would be a great resource for starters getting to know widgets if this was updated

**Comment by Oliver-Binns** [comment]
@kieran-hamill-mobil-i please could you provide more information about the issues you are having?
If you checkout the `going-for-gold` branch, this should support Xcode 12.2 (latest available).

**Comment by Oliver-Binns** [comment]
Closing this issue as I believe it to be fixed.
